# Generated by Django 5.2.8 on 2026-01-17 11:19

import django.db.models.deletion
import site_settings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Category Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
            ],
            options={
                'verbose_name': 'Categories',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Project Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(upload_to='work_images/', verbose_name='Project Image')),
                ('website_logo', models.FileField(blank=True, null=True, upload_to='website_logo/', validators=[site_settings.models.validate_svg_or_image], verbose_name='Website Logo')),
                ('website_url', models.URLField(blank=True, null=True, verbose_name='Website Url')),
                ('priority', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Project Priority')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='projects.category', verbose_name='Project Category')),
            ],
            options={
                'verbose_name': 'Our Works',
                'verbose_name_plural': 'Our Works',
            },
        ),
    ]
