# Generated by Django 5.2.8 on 2026-01-18 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Our Projects', 'verbose_name_plural': 'Our Projects'},
        ),
    ]
