# Generated by Django 5.2.8 on 2026-01-09 14:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Company name')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Sector name')),
            ],
            options={
                'verbose_name': 'Sector',
                'verbose_name_plural': 'Sectors',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExpectedStamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_of_work', models.DecimalField(decimal_places=0, max_digits=19, verbose_name='Value Of Work (A)')),
                ('invoice_copies', models.PositiveIntegerField(verbose_name='Invoice Copies (B)')),
                ('invoice_date', models.DateField(blank=True, null=True, verbose_name='Invoice Date')),
                ('stamp_rate', models.DecimalField(decimal_places=4, default=0.0015, max_digits=6, verbose_name='Stamp rate (C)')),
                ('exchange_rate', models.DecimalField(decimal_places=4, default=1, help_text='سعر الصرف لتحويل القيمة إذا كانت بالعملة الأجنبية', max_digits=10, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Exchange Rate')),
                ('d1', models.DecimalField(blank=True, decimal_places=0, max_digits=19, null=True, verbose_name='Total stamp duty for the claim')),
                ('total_past_years', models.DecimalField(decimal_places=0, default=0, help_text='إجمالي السنوات السابقة لنفس القطاع يتم حسابه تلقائيًا', max_digits=19, verbose_name='Past years total')),
                ('total_stamp_for_company', models.DecimalField(blank=True, decimal_places=0, help_text='الإجمالي بعد جمع كل السنوات السابقة مع الحالي يتم حسابه تلقائيًا', max_digits=19, null=True, verbose_name='Total stamp')),
                ('note', models.TextField(blank=True, help_text='يتم ادخال المصادر هنا اذا وجدت', null=True, verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='expected_stamps', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expected_stamps', to='stamps.sector', verbose_name='Sector')),
            ],
            options={
                'verbose_name': 'Expected Stamp',
                'verbose_name_plural': 'Expected Stamps',
            },
        ),
        migrations.CreateModel(
            name='StampCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_of_work', models.DecimalField(decimal_places=0, max_digits=19, verbose_name='Value Of Work (A)')),
                ('invoice_copies', models.PositiveIntegerField(verbose_name='Invoice Copies (B)')),
                ('invoice_date', models.DateField(blank=True, null=True, verbose_name='Invoice Date')),
                ('stamp_rate', models.DecimalField(decimal_places=4, default=0.0015, max_digits=6, verbose_name='Stamp rate (C)')),
                ('exchange_rate', models.DecimalField(decimal_places=4, default=1, help_text='سعر الصرف لتحويل القيمة إذا كانت بالعملة الأجنبية', max_digits=10, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Exchange Rate')),
                ('d1', models.DecimalField(blank=True, decimal_places=0, max_digits=19, null=True, verbose_name='Total stamp duty for the claim')),
                ('total_past_years', models.DecimalField(decimal_places=0, default=0, help_text='إجمالي السنوات السابقة لنفس الشركة يتم حسابه تلقائيًا', max_digits=19, verbose_name='Past years total')),
                ('total_stamp_for_company', models.DecimalField(blank=True, decimal_places=0, help_text='الإجمالي بعد جمع كل السنوات السابقة مع الحالي يتم حسابه تلقائيًا', max_digits=19, null=True, verbose_name='Total stamp')),
                ('note', models.TextField(blank=True, help_text='يتم ادخال المصادر هنا اذا وجدت', null=True, verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stamp_calculations', to='stamps.company', verbose_name='Company')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='stamp_calculations', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Stamp Calculation',
                'verbose_name_plural': 'Stamp Calculations',
                'ordering': ['-created_at'],
            },
        ),
    ]
