# Generated by Django 5.2.8 on 2025-11-23 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Company name')),
                ('year', models.PositiveIntegerField(verbose_name='Year')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StampCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_of_work', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Value A')),
                ('invoice_copies', models.PositiveIntegerField(verbose_name='Copies B')),
                ('stamp_rate', models.DecimalField(decimal_places=4, default=0.0015, max_digits=6, verbose_name='Stamp rate C')),
                ('d1', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='D1 = A × B × C')),
                ('total_past_years', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Past years total')),
                ('total_stamp_for_company', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Total stamp')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stamp_calculations', to='stamps.company', verbose_name='Company')),
            ],
            options={
                'verbose_name': 'Stamp Calculation',
                'verbose_name_plural': 'Stamp Calculations',
                'ordering': ['-created_at'],
            },
        ),
    ]
