# Generated by Django 5.2.8 on 2026-01-09 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stamps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expectedstamp',
            name='invoice_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Invoice Date'),
        ),
        migrations.AlterField(
            model_name='stampcalculation',
            name='invoice_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Invoice Date'),
        ),
    ]
