# Generated by Django 5.2.8 on 2025-11-24 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stamps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stampcalculation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='stampcalculation',
            name='d1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Total stamp duty for the claim'),
        ),
        migrations.AlterField(
            model_name='stampcalculation',
            name='invoice_copies',
            field=models.PositiveIntegerField(verbose_name='Invoice Copies (B)'),
        ),
        migrations.AlterField(
            model_name='stampcalculation',
            name='stamp_rate',
            field=models.DecimalField(decimal_places=4, default=0.0015, max_digits=6, verbose_name='Stamp rate (C)'),
        ),
        migrations.AlterField(
            model_name='stampcalculation',
            name='total_past_years',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Past years total'),
        ),
        migrations.AlterField(
            model_name='stampcalculation',
            name='total_stamp_for_company',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Total stamp'),
        ),
        migrations.AlterField(
            model_name='stampcalculation',
            name='value_of_work',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Value Of Work (A)'),
        ),
    ]
