# Generated by Django 5.2.8 on 2025-11-24 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stamps', '0004_alter_stampcalculation_d1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stampcalculation',
            name='total_past_years',
            field=models.DecimalField(decimal_places=2, default=0, help_text='إجمالي السنوات السابقة لنفس الشركة يتم حسابه تلقائيًا', max_digits=19, verbose_name='Past years total'),
        ),
        migrations.AlterField(
            model_name='stampcalculation',
            name='total_stamp_for_company',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='الإجمالي بعد جمع كل السنوات السابقة مع الحالي يتم حسابه تلقائيًا', max_digits=19, null=True, verbose_name='Total stamp'),
        ),
    ]
