# Generated by Django 5.2.8 on 2025-11-24 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stamps', '0005_alter_stampcalculation_total_past_years_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stampcalculation',
            name='invoice_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Invoice Year'),
        ),
    ]
