# Generated by Django 5.2.8 on 2025-11-24 19:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stamps', '0006_stampcalculation_invoice_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='stampcalculation',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=4, default=1, help_text='سعر الصرف لتحويل القيمة إذا كانت بالعملة الأجنبية', max_digits=10, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Exchange Rate'),
        ),
    ]
