# Generated by Django 5.2.8 on 2025-11-25 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stamps', '0007_stampcalculation_exchange_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='year',
        ),
    ]
