# Generated by Django 5.2.8 on 2025-11-25 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stamps', '0009_alter_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='stampcalculation',
            name='note',
            field=models.TextField(blank=True, help_text='يتم ادخال المصادر هنا اذا وجدت', null=True, verbose_name='Note'),
        ),
    ]
