# Generated by Django 5.2.8 on 2025-11-26 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stamps', '0010_stampcalculation_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stampcalculation',
            name='d1',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=19, null=True, verbose_name='Total stamp duty for the claim'),
        ),
        migrations.AlterField(
            model_name='stampcalculation',
            name='total_past_years',
            field=models.DecimalField(decimal_places=0, default=0, help_text='إجمالي السنوات السابقة لنفس الشركة يتم حسابه تلقائيًا', max_digits=19, verbose_name='Past years total'),
        ),
        migrations.AlterField(
            model_name='stampcalculation',
            name='total_stamp_for_company',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='الإجمالي بعد جمع كل السنوات السابقة مع الحالي يتم حسابه تلقائيًا', max_digits=19, null=True, verbose_name='Total stamp'),
        ),
        migrations.AlterField(
            model_name='stampcalculation',
            name='value_of_work',
            field=models.DecimalField(decimal_places=0, max_digits=19, verbose_name='Value Of Work (A)'),
        ),
    ]
