# Generated by Django 5.2.8 on 2025-11-26 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stamps', '0011_alter_stampcalculation_d1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stampcalculation',
            name='invoice_year',
        ),
        migrations.AddField(
            model_name='stampcalculation',
            name='invoice_date',
            field=models.DateField(blank=True, null=True, verbose_name='Invoice Date'),
        ),
    ]
