# Generated by Django 5.2.8 on 2025-12-07 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='syndicate_number',
            field=models.CharField(error_messages={'unique': 'Profile with this Syndicate Number already exists.'}, max_length=50, unique=True, verbose_name='Syndicate Number'),
        ),
    ]
