# Generated by Django 6.0.1 on 2026-02-07 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_created_at_alter_profile_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='judicial_seizure',
            field=models.BooleanField(blank=True, null=True, verbose_name='Judicial seizure'),
        ),
    ]
