# Generated by Django 5.2.8 on 2025-11-12 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_logo', models.ImageField(blank=True, null=True, upload_to='site_logos/', verbose_name='Site Logo')),
                ('about_site', models.TextField(blank=True, null=True, verbose_name='About Site')),
                ('copyright_info', models.CharField(blank=True, max_length=255, null=True, verbose_name='Copyright Info')),
                ('instagram_link', models.URLField(blank=True, null=True, verbose_name='Instagram Link')),
                ('facebook_link', models.URLField(blank=True, null=True, verbose_name='Facebook Link')),
                ('linkedIn_link', models.URLField(blank=True, null=True, verbose_name='LinkedIn Link')),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configurations',
            },
        ),
    ]
