# Generated by Django 5.2.8 on 2025-11-12 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='site_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Site Name'),
        ),
    ]
