# Generated by Django 5.2.8 on 2025-12-22 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0002_page_seosettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='number_of_retired_engineers',
            field=models.PositiveIntegerField(default=0, verbose_name='Number of Retired Engineers'),
        ),
    ]
