# Generated by Django 5.2.8 on 2026-01-18 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0003_siteconfiguration_number_of_retired_engineers'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
