# Generated by Django 6.0.1 on 2026-01-27 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0004_page_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='current_pension',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Current Pension'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='pension_description',
            field=models.TextField(blank=True, null=True, verbose_name='Pension Description'),
        ),
    ]
