# Generated by Django 6.0.1 on 2026-01-31 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0005_siteconfiguration_current_pension_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAllowedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True, verbose_name='IP Address')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='IP Address Description')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
            ],
            options={
                'verbose_name': 'Allowed Admin IP',
                'verbose_name_plural': 'Allowed Admin IPs',
            },
        ),
    ]
