# Generated by Django 5.2.8 on 2025-11-12 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_content_file_content_image_alter_content_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['title'], 'verbose_name': 'Content', 'verbose_name_plural': 'Contents'},
        ),
    ]
